site_name: CSC behavior guidelines
site_url: https://rulebook.csconfederation.com
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
nav:
    - Punishment Legend: punishment-legend.md
    - Behavior Guidelines: behavior-guidelines.md
    - Detailed Misbehavior Descriptions: detailed-misbehavior-descriptions.md
    - Notes: notes.md
